"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.NETWORKS = exports.NOTE_STATUS = exports.START_EVENTS_SYNCING_BLOCK = exports.MIN_BYTES_VAR_LENGTH = exports.DYNAMIC_VAR_CONFIG_LENGTH = exports.AZTEC_JS_METADATA_PREFIX_LENGTH = exports.METADATA_AZTEC_DATA_LENGTH = exports.VIEWING_KEY_LENGTH = exports.REAL_VIEWING_KEY_LENGTH = exports.EXTENSION_PUBLIC_KEY_LENGTH = exports.USER_PUBLIC_KEY_LENGTH = exports.ADDRESS_LENGTH = void 0;
// exluding 0x
var ADDRESS_LENGTH = 40;
exports.ADDRESS_LENGTH = ADDRESS_LENGTH;
var USER_PUBLIC_KEY_LENGTH = 66;
exports.USER_PUBLIC_KEY_LENGTH = USER_PUBLIC_KEY_LENGTH;
var EXTENSION_PUBLIC_KEY_LENGTH = 64;
exports.EXTENSION_PUBLIC_KEY_LENGTH = EXTENSION_PUBLIC_KEY_LENGTH;
var REAL_VIEWING_KEY_LENGTH = 138;
exports.REAL_VIEWING_KEY_LENGTH = REAL_VIEWING_KEY_LENGTH;
var VIEWING_KEY_LENGTH = 420;
exports.VIEWING_KEY_LENGTH = VIEWING_KEY_LENGTH;
var METADATA_AZTEC_DATA_LENGTH = 194;
exports.METADATA_AZTEC_DATA_LENGTH = METADATA_AZTEC_DATA_LENGTH;
var AZTEC_JS_METADATA_PREFIX_LENGTH = 130;
exports.AZTEC_JS_METADATA_PREFIX_LENGTH = AZTEC_JS_METADATA_PREFIX_LENGTH;
var DYNAMIC_VAR_CONFIG_LENGTH = 64;
exports.DYNAMIC_VAR_CONFIG_LENGTH = DYNAMIC_VAR_CONFIG_LENGTH;
var MIN_BYTES_VAR_LENGTH = 64;
exports.MIN_BYTES_VAR_LENGTH = MIN_BYTES_VAR_LENGTH;
var START_EVENTS_SYNCING_BLOCK = 0;
exports.START_EVENTS_SYNCING_BLOCK = START_EVENTS_SYNCING_BLOCK;
var NOTE_STATUS = {
  CREATED: 'CREATED',
  DESTROYED: 'DESTROYED'
};
exports.NOTE_STATUS = NOTE_STATUS;
var NETWORKS = {
  GANACHE: {
    id: 0,
    networkName: 'ganache'
  },
  MAIN: {
    id: 1,
    networkName: 'mainnet'
  },
  ROPSTEN: {
    id: 3,
    networkName: 'ropsten'
  },
  RINKEBY: {
    id: 4,
    networkName: 'rinkeby'
  },
  GOERLI: {
    id: 5,
    networkName: 'goerli'
  },
  KOVAN: {
    id: 42,
    networkName: 'kovan'
  }
};
exports.NETWORKS = NETWORKS;